---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-prod
  namespace: production
spec:
  selector:
    matchLabels:
      name: wp-prod
  template:
    metadata:
      labels:
        name: wp-prod
    spec:
      containers:
      - name: wp-prod
        image: coolninja/wordpress
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: wpsecret
                key: DB_HOST
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: wpsecret
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: wpsecret
                key: DB_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: wpsecret
                key: DB_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: wp-prod
  namespace: production
spec:
  #type: LoadBalancer
  ports:
    - port: 80
  selector:
    name: wp-prod
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wp-prod-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: wp.donorplasma.id
      http:
        paths:
          #- path: /belajar
          - backend:
              serviceName: wp-prod
              servicePort: 80
