# apiVersion: cert-manager.io/v1alpha2
# kind: Issuer
# metadata:
#  name: landing-page-production
#  namespace: landing-page-production
# spec:
#  acme:
#    # The ACME server URL
#    server: https://acme-v02.api.letsencrypt.org/directory
#    # Email address used for ACME registration
#    email: gerald.gunasha@gmail.com
#    # Name of a secret used to store the ACME account private key
#    privateKeySecretRef:
#      name: landing-page-production
#    # Enable the HTTP-01 challenge provider
#    solvers:
#    - selector: {}
#      http01:
#        ingress:
#          class:  nginx
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page-production
  namespace: landing-page-production
spec:
  replicas: 3
  selector:
    matchLabels:
      name: landing-page-production
  template:
    metadata:
      labels:
        name: landing-page-production
    spec:
      containers:
      - name: landing-page-production
        image: vanillavladimir/landing_page
---
apiVersion: v1
kind: Service
metadata:
  name: landing-page-production
  namespace: landing-page-production
spec:
  #type: LoadBalancer
  ports:
    - port: 80
  selector:
    name: landing-page-production
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: landing-page-ingress
  namespace: landing-page-production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "landing-page-production"
spec:
  rules:
    - host: landingpage.production.vladgerald.tech
      http:
        paths:
          #- path: /belajar
          - backend:
              serviceName: landing-page-production
              servicePort: 80
  tls:
    - hosts:
        - landingpage.production.vladgerald.tech
      secretName: landing-page-tls
