apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
 name: landing-page-production
 namespace: landing-page-production
spec:
 acme:
   # The ACME server URL
   server: https://acme-v02.api.letsencrypt.org/directory
   # Email address used for ACME registration
   email: gerald.gunasha@gmail.com
   # Name of a secret used to store the ACME account private key
   privateKeySecretRef:
     name: landing-page-production
   # Enable the HTTP-01 challenge provider
   solvers:
   - selector: {}
     http01:
       ingress:
         class:  nginx