---
apiVersion: v1
kind: Secret
metadata:
  name: wpsecret
type: Opaque
data:
  DB_USER: cm9vdA==
  DB_PASS: bWFzdWthamE=
  DB_HOST: ZGJnZXJhbGQuY3V3d2pweTBsaDY1LmFwLXNvdXRoZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
  DB_NAME: d29yZHByZXNz
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wp-stag
  namespace: stagging
spec:
  selector:
    matchLabels:
      app: wp-stag
  template:
    metadata:
      labels:
        app: wp-stag
    spec:
      containers:
        - name: wp-stag
          image: coolninja/wordpress
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: wpsecret
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: wpsecret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: wpsecret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: wpsecret
                  key: DB_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: wp-stag
  namespace: wp-stag
spec:
  #type: LoadBalancer
  ports:
    - port: 80
  selector:
    name: wp-stag
---
# apiVersion: extensions/v1beta1
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wp-staging-ingress
  namespace: stagging
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "wp-staging"
spec:
  rules:
    - host: wp-stag.donorplasma.id
      http:
        paths:
          #- path: /belajar
          - backend:
              service:
                name: wp-stag
                port:
                  number: 80
