apiVersion: apps/v1
kind: Deployment
metadata:
  name: pesbuk-prod
  namespace: production
spec:
  selector:
    matchLabels:
      name: pesbuk-prod
  template:
    metadata:
      labels:
        name: pesbuk-prod
    spec:
      containers:
      - name: pesbuk-production
        image: coolninja/sosmed
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: pesbuksecret
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: pesbuksecret
                key: DB_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: pesbuksecret
                key: DB_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: pesbuk-prod
  namespace: production
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    name: pesbuk-production
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pesbuk-production-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: sosmed.donorplasma.id
      http:
        paths:
          #- path: /belajar
          - backend:
              serviceName: pesbuk-production
              servicePort: 80
