apiVersion: v1
kind: Secret
metadata:
  name: pesbuksecret
  namespace: production
type: Opaque
data:
  DB_USER: cm9vdA==
  DB_PASS: bWFzdWthamE=
  DB_HOST: ZGJnZXJhbGQuY3V3d2pweTBsaDY1LmFwLXNvdXRoZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
  DB_NAME: d29yZHByZXNz
