---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: landingpage-stag
  namespace: stagging
spec:
  selector:
    matchLabels:
      name: landingpage-stag
  template:
    metadata:
      labels:
        name: landingpage-stag
    spec:
      containers:
        - name: landingpage-stag
          image: coolninja/landingpage
---
apiVersion: v1
kind: Service
metadata:
  name: landingpage-stag
  namespace: stagging
spec:
  #type: LoadBalancer
  ports:
    - port: 80
  selector:
    name: landingpage-stag
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: landing-page-ingress
  namespace: landing-page-staging
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    #cert-manager.io/issuer: "landing-page-staging"
spec:
  rules:
    - host: dev.donorplasma.id
      http:
        paths:
          #- path: /belajar
          - backend:
              serviceName: landingpage-stag
              servicePort: 80
